// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"mado/models"
)

// GetTodosReader is a Reader for the GetTodos structure.
type GetTodosReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetTodosReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetTodosOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /todos] GetTodos", response, response.Code())
	}
}

// NewGetTodosOK creates a GetTodosOK with default headers values
func NewGetTodosOK() *GetTodosOK {
	return &GetTodosOK{}
}

/*
GetTodosOK describes a response with status code 200, with default header values.

An array of todos
*/
type GetTodosOK struct {
	Payload []*models.Todo
}

// IsSuccess returns true when this get todos o k response has a 2xx status code
func (o *GetTodosOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get todos o k response has a 3xx status code
func (o *GetTodosOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get todos o k response has a 4xx status code
func (o *GetTodosOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get todos o k response has a 5xx status code
func (o *GetTodosOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get todos o k response a status code equal to that given
func (o *GetTodosOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get todos o k response
func (o *GetTodosOK) Code() int {
	return 200
}

func (o *GetTodosOK) Error() string {
	return fmt.Sprintf("[GET /todos][%d] getTodosOK  %+v", 200, o.Payload)
}

func (o *GetTodosOK) String() string {
	return fmt.Sprintf("[GET /todos][%d] getTodosOK  %+v", 200, o.Payload)
}

func (o *GetTodosOK) GetPayload() []*models.Todo {
	return o.Payload
}

func (o *GetTodosOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
